config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "restaurants#index"

  resources :restaurants, only: [:index, :new, :create, :show, :edit, :update, :destroy] do
    resources :reviews, only: [:new, :create, :destroy]
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  CATEGORIES = ["chinese", "italian", "japanese", "french", "belgian"]

  belongs_to :user
  has_many :reviews, dependent: :destroy

  validates :name, presence: true
  validates :address, presence: true
  validates :category, presence: true, inclusion: { in: CATEGORIES }
end

app/models/review.rb
class Review < ApplicationRecord
  RATING = (0..5).to_a

  belongs_to :restaurant
  belongs_to :user

  validates :content, presence: true
  validates :rating, presence: true, inclusion: { in: RATING }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :first_name, presence: true
  validates :last_name, presence: true
  has_many :restaurants
  has_many :reviews

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]

  def index
    @restaurants = Restaurant.all
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    @restaurant.user_id = current_user.id

    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @reviews = @restaurant.reviews
    # @review.restaurant = @restaurant
  end

  def edit
  end

  def update
    if @restaurant.update(restaurant_params)
      redirect_to restaurant_path(@restaurant)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    if @restaurant.destroy
      redirect_to restaurants_path
    else
      render :show, status: :unprocessable_entity
    end
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category, :user_id)
  end

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new(review_params)
    @review.restaurant_id = @restaurant.id
    @review.user_id = current_user.id

    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @restaurant = Restaurant.find(params[:id])
    @review = Review.find(params[:restaurant_id])
    # raise

    if @review.destroy
      redirect_to restaurant_path(@restaurant)
    else
      redirect_to restaurant_path(@restaurant)
    end
  end

  private

  def review_params
    params.require(:review).permit(:rating, :content, :restaurant_id, :user_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>YieldMvp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <header>
      <div class="navbar navbar-expand-sm navbar-light navbar-lewagon">

  <div class="container-fluid">
    <%= link_to "Home", root_path, class: "navbar-brand"%>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
                <a class="button-black" data-bs-toggle="modal" data-bs-target="#exampleModal" >Créer</a>
          </li>

          <li class="nav-item dropdown">
            <%# <%= image_tag "photo2.jpg", width:100, height: 100, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %> %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Contact", "#", class: "dropdown-item" %>
              <%= link_to "À propos", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, class: "dropdown-item", data: {turbo_method: :delete} %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

    </header>
    <%= yield %>
  </body>
</html>

app/views/restaurants/_form_new_restaurant.html.erb
<div class="container">
  <%= simple_form_for(restaurant) do |f| %>
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :category, collection: Restaurant::CATEGORIES %>
    <%= f.submit %>
  <% end %>
</div>

app/views/restaurants/_form_restaurant.html.erb
<div class="container">
  <%= simple_form_for(restaurant) do |f| %>
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :category, collection: Restaurant::CATEGORIES %>
    <%= f.input :phone_number %>
    <%= f.submit %>
  <% end %>
</div>

app/views/restaurants/edit.html.erb
<%= render partial: "form_restaurant", locals: {restaurant: @restaurant} %>

app/views/restaurants/index.html.erb
<h1>Here are all Restaurants</h1>

<p><%= link_to "Create a restaurant", new_restaurant_path %></p>

<% @restaurants.each do |r| %>
  <ul>
    <li><h2><%= link_to r.name, restaurant_path(r) %></h2></li>
    <li>Category: <%= r.category.capitalize %></li>
    <li><p>Address: <%= r.address %></p></li>
  </ul>
<% end %>

app/views/restaurants/new.html.erb
<%= render partial: "form_restaurant", locals: {restaurant: @restaurant} %>

app/views/restaurants/show.html.erb
<h1><%= @restaurant.name %></h1>

<p><%= link_to "back home", restaurants_path %></p>

<ul>
  <li>Category: <%= @restaurant.category.capitalize %></li>
  <li>Address: <%= @restaurant.address %></li>
  <li>By: <%= @restaurant.user.first_name %></li>
</ul>

<h3>Reviews</h3>

<% @reviews.each do |r| %>
  <ul>
    <li><%= r.user.first_name %>: "<%= r.content %>"</li>
    <li>Rate: <%= r.rating %>/5</li>
    <li><%= link_to "Delete review", restaurant_review_path(r), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %></li>
  </ul>
<% end %>

<p><%= link_to "Add a review", new_restaurant_review_path(@restaurant) %></p>
<p><%= link_to "Edit Restaurant", edit_restaurant_path(@restaurant) %></p>
<p><%= link_to "Delete this Restaurant", restaurant_path(@restaurant), data: { turbo_method: :delete, turbo_confirm: "Are you sure?"} %></p>

app/views/reviews/_form_review.html.erb
<div class="container">
  <%= simple_form_for [restaurant, review] do |f| %>
    <%= f.input :content %>
    <%= f.input :rating, collection: Review::RATING %>
    <%= f.submit %>
  <% end %>
</div>

app/views/reviews/new.html.erb
<%= render partial: "form_review", locals: {review: @review, restaurant: @restaurant} %>